#!/usr/bin/env bash

Src=$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )

alias ls="ls -G"
alias gp="git add *; git commit -am saving; git push; git status"
alias axe="lua axe.lua"
alias ok="lua tests.lua"

docs() {
  cd $Src
  pycco  *.lua
  cp etc/pycco.css docs/
}

