#!/usr/bin/env bash
# vim : set syntax=sh :
export BASH_SILENCE_DEPRECATION_WARNING=1

D=lua/pipes

alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias gp="git add * ; git commit -am saving; git push; git status";
alias grep='grep --color=auto'
alias ls="ls -G"
alias ed="nvim -u $H/$D/etc/nvimrc -p ";

,() { 
  f=$1.lua; shift; lua $f $*; 
}

hello() {
	NO='\033[0m'
	RED='\033[0;31m'
	GREEN='\033[0;32m'
	ORANGE='\033[0;33m'
	BLUE='\033[0;34m'
	PURPLE='\033[0;35m'
	CYAN='\033[0;36m'
	LIGHTGRAY='\033[0;37m'
	DARKGRAY='\033[1;30m'
	LIGHTRED='\033[1;31m'
	LIGHTGREEN='\033[1;32m'
	YELLOW='\033[1;33m'
	LIGHTBLUE='\033[1;34m'
	LIGHTPURPLE='\033[1;35m'
	LIGHTCYAN='\033[1;36m'
	WHITE='\033[1;37m'
	clear
	echo -e "$NO$ORANGE"
  echo " _   _|_   _   /  |_" 
  echo "(/_   |_  (_  /   | | "
	echo -e "$NO$LIGHTRED"
	echo "Short cuts:"; echo ""
	alias | sed 's/alias /  /'
	echo -e "$NO$ORANGE"; 
	$H/$D/etc/art
  echo -e "$NO"
}

pdf() {
	mkdir -p ~/tmp
	echo "pdf-ing $1 ... "
	a2ps                          \
		-Br                          \
		--chars-per-line 105          \
		--file-align=fill              \
		--line-numbers=1                \
		--borders=no                     \
		--pro=color                       \
		--columns  3                       \
		-M letter                           \
		--pretty-print="$H/$D/etc/lua.ssh"   \
		-o ~/tmp/$1.ps $1.lua
	ps2pdf ~/tmp/$1.ps ~/tmp/$1.pdf;  rm ~/tmp/$1.ps
  open ~/tmp/$1.pdf
}

here()    { cd $1; basename `pwd`; }
PROMPT_COMMAND='echo -ne "📐 $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'

if [ -z "$H" ] 
then H=`git rev-parse --show-toplevel`
     hello
     H="$H" bash --init-file $H/$D/etc/h -i
fi
