" https://dev.to/elvessousa/my-basic-neovim-setup-253l
let mapleader = " "

" Install vundle
let shouldInstallBundles = 0

if !filereadable($HOME . "/.config/nvim/autoload/plug.vim")
  echo "~≥ Installing vim-plug \n"
  silent !curl -fLo $HOME/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  let shouldInstallBundles = 1
endif

" Plugins
call plug#begin('~/.config/nvim/plugged')
Plug 'wincent/terminus'
Plug 'tpope/vim-vinegar'
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'romainl/Apprentice',{'as':'apprentice'}
Plug 'powerline/powerline'
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
Plug 'bluz71/vim-nightfly-colors', { 'as': 'nightfly' }

call plug#end()


if shouldInstallBundles == 1
    echo "~> Installing plugs\n"
    :PlugInstall
endif

colorscheme nightfly

set noswapfile nowritebackup nobackup
set ignorecase
set visualbell
set nowrap
set termguicolors

" Indendation
set autoindent smarttab expandtab
set shiftround tabstop=2 shiftwidth=2
set pastetoggle=<F2>

set ts=2
set sw=2
set sts=2
set et

set clipboard=unnamedplus
set completeopt=noinsert,menuone,noselect
set cursorline
set hidden
set mouse=a
set number
set relativenumber
set splitbelow splitright
set title
set ttimeoutlen=0
set wildmenu

" Search
set gdefault
set ignorecase smartcase

filetype plugin indent on
syntax on

set t_Co=256
" True color if available
let term_program=$TERM_PROGRAM

" Check for conflicts with Apple Terminal app
if term_program !=? 'Apple_Terminal'
    set termguicolors
else
    if $TERM !=? 'xterm-256color'
        set termguicolors
    endif
endif


