import re
RULES=[  # (regex on lowercased raw target, canonical name)
 (r'\bmoot\b(?!.*source)|moot repository|moot task sources|moot0', 'MOOT repository'),
 (r'moot source: chen & chen promisetune|promisetune', 'PromiseTune config data (Chen & Chen)'),
 (r'moot source: chen, gong|chen, gong|accuracy can lie|sql_allmeas', 'Chen, Gong & Chen config data (Accuracy can lie)'),
 (r'moot source: chen, nair|chen, nair & menzies|pom3|xomo|coc1000|process[- ]model datasets|nasa93dem|beyond-evolutionary|gale sbse|\bsampling\b.*baseline optimizer|rrp /', 'POM3 / XOMO / COC1000 process models (Chen, Nair, Menzies)'),
 (r'moot source: lustosa & menzies isneak|isneak|scrum1k|scrum and pom3|feature-model data', 'iSNEAK feature-model data (Lustosa & Menzies)'),
 (r'project health|health-closed|health-easy|hpo project-health', 'Project health datasets (Lustosa & Menzies)'),
 (r'moot source: nair|nair et al|ss-\*|ss-a|spectral-learning|data-driven sbse|flash', 'SS-* config datasets / FLASH (Nair et al.)'),
 (r'moot source: peng|veer', 'VEER config data (Peng et al.)'),
 (r'rayegan & menzies data|rayegan.*(ss-|config)|software config \(ss', 'Config/testing data (Rayegan & Menzies)'),
 (r'senthilkumar.*(data|apache|cloud)|cloud tuning datasets', 'Cloud tuning data (Senthilkumar & Menzies)'),
 (r'kaggle|fifa|all_players|player_statistics|bankchurners|telco|student.dropout|life.expectancy|covid|hospital|marketing_analytics|car_price|home_data|loan \(|hr-employee|ibm hr|animal crossing|accessories, dress', 'Kaggle cross-domain datasets'),
 (r'^uci|adult \(census|bank marketing|diabetes dataset|heart disease|iris dataset|magic gamma|statlog|default of credit|household electric', 'UCI datasets'),
 (r'promise repository|nasa defect data', 'PROMISE repository (NASA defect data)'),
 (r'\bsmac\b|smac3', 'SMAC / SMAC3 (Hutter; Lindauer)'),
 (r'\bdehb\b', 'DEHB (Awad, Mallik, Hutter)'),
 (r'\btpe\b|tree-structured parzen|tree of parzen', 'TPE (Bergstra et al.)'),
 (r'\bezr\b|lite optimizer|line / kpp', 'EZR / LITE (Menzies group)'),
 (r'optuna', 'OPTUNA (Akiba et al.)'),
 (r'random search \(bergstra|random search baseline|random sampling baseline|bergstra et al\. warning', 'Random search baseline (Bergstra & Bengio; Arcuri & Briand)'),
 (r'scott-knott|top-set ranking', 'Scott-Knott ranking'),
 (r"cliff", "Cliff's delta effect size"),
 (r'bootstrap', 'Bootstrap significance test (Efron)'),
 (r'kolmogorov', 'Kolmogorov-Smirnov test'),
 (r"cohen.*(small|0\.2|sawilowsky|indistinguish)|sawilowsky 0\.35", "Cohen / Sawilowsky small-effect rule"),
 (r'cohen.*(straw|simple baselines)|reference.optim', "Reference-optimal / straw-man baseline (Cohen; McGeoch)"),
 (r'k-?means\+\+|kpp', 'K-means++ seeding (Arthur & Vassilvitskii)'),
 (r'kmeans clustering', 'K-means (MacQueen)'),
 (r'chebyshev|moea/d', 'Chebyshev distance / MOEA-D (Zhang & Li)'),
 (r'd2h|distance-to-heaven|distance-to-ideal|normalized regret', 'Distance-to-heaven (d2h) metric'),
 (r'\blime\b', 'LIME (Ribeiro et al.)'),
 (r'\bshap\b(?!fuzz)', 'SHAP (Lundberg & Lee)'),
 (r'relieff', 'ReliefF (Robnik-Sikonja & Kononenko)'),
 (r'nsga-ii \(', 'NSGA-II (Deb et al.)'),
 (r'spea2|zitzler', 'SPEA2 (Zitzler et al.)'),
 (r'li, chen & yao|li, chen, yao|igd/hv|frontier-aware metrics|argument that hv|pareto-based sbse evaluation|pareto sbse evaluation', 'Pareto metric guidance (Li, Chen & Yao)'),
 (r'hamlet|probable correctness', "Hamlet's probable correctness theory"),
 (r'agrawal.*(intrinsic|threshold|fractal)|fractal intrinsic', 'Intrinsic dimensionality (Agrawal et al.)'),
 (r'lustosa & menzies drr|drr \(', 'DRR effect (Lustosa & Menzies)'),
 (r'ganguly & menzies|menzies & ganguly|prior moot benchmark|how low can you go|bingo|b<=20', 'Prior EZR-vs-SMAC results (Ganguly & Menzies)'),
 (r'senthilkumar & menzies(?!.*data)|warm-start|synthcore|bs_llm', 'LLM warm-start results (Senthilkumar & Menzies)'),
 (r'rayegan & menzies', 'Rayegan & Menzies (tiny trees / causality)'),
 (r'menzies & srinivasan|150-label', 'Menzies & Srinivasan (label saturation)'),
 (r'fuzzilli', 'Fuzzilli (Gross et al.)'),
 (r'gemini', 'Gemini (Google)'),
 (r'gpt-|openai api|chatgpt|gpt-oss', 'OpenAI GPT models / API'),
 (r'deepseek', 'DeepSeek models / API'),
 (r'llama|code llama|codellama', 'Llama / Code Llama (Meta)'),
 (r'welford', "Welford's incremental algorithm"),
 (r'empirical standards', 'ACM SIGSOFT Empirical Standards (Ralph et al.)'),
 (r'hou et al|llm4se systematic', 'Hou et al. LLM4SE SLR'),
 (r'shepperd.*nasa|nasa data quality|herbold', 'Defect-data quality problems (Shepperd; Herbold)'),
 (r'xgboost', 'XGBoost (Chen & Guestrin)'),
 (r'scikit-learn', 'scikit-learn'),
 (r'shypula|pie ', 'PIE (Shypula et al.)'),
 (r'effibench|effilearner', 'EffiBench / EffiLearner (Huang et al.)'),
 (r'humaneval|mbpp|evalplus|apps benchmark|codecontests|papers with code', 'Code-generation benchmarks (HumanEval, MBPP, APPS, CodeContests)'),
 (r'settles', 'Active-learning taxonomy (Settles)'),
 (r'demsar|win/tie/loss', 'Win/tie/loss comparison (Demsar)'),
 (r'kampenes', 'Effect-size guidance (Kampenes et al.)'),
 (r'aha', "Aha's mixed-data distance"),
 (r'yu.*slr|fastread|wahono|hall et al\. fault|radjenovic|kitchenham & brereton', "Yu et al. SLR corpora / FASTREAD"),
 (r'hutter.*random-forest surrogate|random-forest surrogate|surrogate nas|yahpo|nearest-neigh.*surrogate', 'Surrogate-oracle evaluation protocol (YAHPO; Eggensperger)'),
 (r'chen & li|pareto-vs-weighted', 'Pareto-vs-weighted SBSE (Chen & Li)'),
 (r'hort & sarro|nsga-ii population', 'NSGA-II population-size evidence (Hort & Sarro)'),
 (r'valov', 'x264 exhaustive cost (Valov et al.)'),
 (r'tantithamthavorn', 'Defect-predictor tuning (Tantithamthavorn et al.)'),
 (r'ostrand|hamill|fault concentration', 'Fault concentration (Ostrand; Hamill)'),
 (r'grinsztajn|shwartz-ziv|tabular data survey|somvanshi', 'Tree models beat DL on tabular data (Grinsztajn; Shwartz-Ziv)'),
 (r'v8 |mjsunit|chromium|jsvu', 'V8 engine / mjsunit / PoCs'),
 (r'die \(park|aspect-preserving|fuzzjit', 'JS-engine fuzzers (DIE, FuzzJIT)'),
 (r'magicoder|evol-instruct|self-oss-instruct|starcoder|wizardcoder', 'Code LLM training sets and models (Magicoder, StarCoder, WizardCoder)'),
 (r'mistral|mixtral|codestral|devstral|qwen|phi-3|gemma', 'Other open LLMs (Mistral, Qwen, Phi, Gemma)'),
 (r'anthropic|claude', 'Claude (Anthropic)'),
 (r'deep infra|openrouter', 'LLM hosting APIs (Deep Infra, OpenRouter)'),
 (r'simulated annealing|kirkpatrick', 'Simulated annealing (Kirkpatrick et al.)'),
 (r'menzies, greenwald|menzies retrospective|shockingly simple', 'Menzies 2007 defect-prediction protocol'),
 (r'feldt & magazinius', 'Threats-to-validity framework (Feldt & Magazinius)'),
 (r'wohlin', 'Empirical SE guidelines (Wohlin et al.)'),
 (r'permutation importance|alcaide|biecek', 'Permutation importance (Biecek; Alcaide)'),
 (r'mean decrease in impurity|breiman', 'Random forests (Breiman)'),
 (r'chain-of-thought|self-refine|opro|multi-agent debate|role identification|iterative validation|contracts/postconditions|llms fail to follow|normtab|few-shot prompting|instruction prompting|generator-based', 'LLM prompting techniques (CoT, Self-refine, OPRO, ...)'),
 (r'coverage\.py|line_profiler|cirron|docker\b', 'Profiling / infra tools (coverage.py, line_profiler, Cirron, Docker)'),
 (r'genetic algorithm|hill climbing|tabu search|differential evolution|\(1\+1\)-es|pso |eda \(|iterated local search|local search with reset|1990s local-search|sms-emoa|epsilon-domination', 'Classic search heuristics (GA, HC, Tabu, DE, ES, PSO, ILS, ...)'),
 (r'dbscan|hdbscan|cure clustering|fastmap', 'Clustering methods (DBSCAN, HDBSCAN, CURE, Fastmap)'),
 (r'gaussian process|brochu', 'GP-UCB Bayesian optimization (Brochu)'),
 (r'landscape|dispersion metric|fitness-distance|instance-space|nearest-better', 'Landscape analysis features (Lunacek; Jones & Forrest; Kerschke)'),
 (r'no-free-lunch', 'No-Free-Lunch theorem (Wolpert & Macready)'),
 (r'hoeffding|reward-free|geometric waiting', 'Sample-complexity bounds (Hoeffding; Jin; Ross)'),
 (r'price.s square|monperrus|iclr points|lottery-based|neurips 2014|registered reports|human\+ai review', 'Peer-review / science-of-science evidence'),
 (r'pearl|poole|hoffman|anchors|breakdown', 'XAI / causality frameworks (Pearl, Hoffman, Anchors, BreakDown)'),
 (r'xai-as-feature-selection|weighted jaccard|anova feature|regression baselines|lightgbm', 'XAI-as-feature-selection protocol and baselines'),
 (r'kohavi|walk-forward|falessi|pred40|standardized accuracy|sarro', 'Validation / effort-estimation metrics (Kohavi; Falessi; Sarro; Shepperd)'),
 (r'jamshidi|guo et al|ha & zhang|deepperf|muhlbauer|weber et al|krishna et al|beetle|fu, menzies|tuning-for-analytics|hulse|feather & menzies|mathew et al|boehm cocomo', 'Config-tuning and analytics data (Fu; Jamshidi; Guo; Ha; Weber; Krishna)'),
 (r'complementary naive bayes', 'Complementary Naive Bayes (Rennie et al.)'),
 (r'explore/exploit', 'Explore/exploit active learners (Lustosa & Menzies)'),
 (r'swa y|\bsway\b|plain samplers', 'SWAY / plain samplers (Chen et al.)'),
 (r'dodge', 'DODGE (Agrawal et al.)'),
 (r'agrawal.*(nondeterminism|se optimization)|learner nondeterminism', 'Agrawal et al. (tuning / SE-specific optimizers)'),
 (r'semenova|rashomon', 'Rashomon ratio (Semenova, Rudin)'),
 (r'wilcoxon|mann-whitney', 'Wilcoxon / Mann-Whitney test'),
 (r'expert-elicitation|valerdi', 'Expert-elicitation label rate (Valerdi)'),
 (r'priorband', 'PriorBand (Mallik et al.)'),
 (r'colanzi', 'SSBSE usage survey (Colanzi et al.)'),
 (r'replication package \(paretomyth|optimizertournament replication', "Authors' own replication package"),
 (r'originating-paper default', 'Originating-paper default hyperparameters'),
 (r'prior config-optimization work|prior studies using pre-labeled', 'Prior config-optimization studies (few datasets)'),
 (r'hindle|tempero|martin.s clean|martinez & duran|declining bug|elahi|michael & jones|wong & mathur|kocaguneli|montage|optfuzz|fuzz4all|bigfuzz|shapfuzz', 'Software-engineering folklore and fuzzing observations'),
 (r'patterson & hennessy|pass@k|test leakage|sbllm|coffe fse', 'Code-efficiency evaluation conventions (pass@k, TLI, COFFE, SBLLM)'),
 (r'huang et al\. finding|llm-driven feature generation|ahmed et al|di fiore|hess & kromrey|gain-ratio|ensemble methods rationale|irwin-hall|hoare quickselect|johnson', 'Misc method justifications'),
 (r'chen et al\. sampling baseline|regret-reduction', 'Regret / random-floor protocol (Chen et al.)'),
 (r'sat backdoors|feature.based algorithm', 'SAT backdoors (Williams, Gomes, Selman)'),
 (r'yu et al\., jitterbug|unreliable technical-debt', 'Unreliable TD labels (Yu et al.)'),
 (r'defect-prediction slr|kitchenham', "Yu et al. SLR corpora / FASTREAD"),
]
def canon(raw):
    t=raw.lower()
    for rx,name in RULES:
        if re.search(rx,t): return name
    return raw

# --- rules added for the top25 corpus (defect prediction, transfer learning, effort estimation, SLR) ---
EXTRA=[
 (r'\ba12\b|vargha|delaney', "A12 effect size (Vargha & Delaney; Arcuri & Briand)"),
 (r'\bsmote\b', 'SMOTE (Chawla et al.)'),
 (r'nsga-?ii', 'NSGA-II (Deb et al.)'),
 (r'scikit|sklearn', 'scikit-learn'),
 (r'\bweka\b', 'Weka'),
 (r'static bug finders vs stat|rahman.*static', 'Static bug finders vs statistical models (Rahman et al.)'),
 (r'fftree|fast and frugal', 'Fast-and-frugal trees (Chen et al.; Phillips)'),
 (r'hall.*slr|wahono|radjenovic|kitchenham.*(slr|corp)|slr dataset', 'Yu et al. SLR corpora / FASTREAD'),
 (r'\baeeem\b|d.ambros', 'AEEEM defect data (D Ambros et al.)'),
 (r'relink', 'ReLink defect data (Wu et al.)'),
 (r'\bmorph\b', 'MORPH defect data (Peters & Menzies)'),
 (r'nasa.*(mdp|defect|cleaned|ds0)|cleaned nasa|softlab|promise.*(nasa|defect)|promise repository|\bpromise\b|seacraft|tera-?promise', 'PROMISE / SEACRAFT repository (NASA, SOFTLAB, Jureczko)'),
 (r'jureczko|apache.*(defect|ck)|ck metrics', 'Jureczko Apache CK-metric defect data'),
 (r'no.free.lunch', 'No-Free-Lunch theorem (Wolpert & Macready)'),
 (r'logistic regression', 'Logistic regression'),
 (r'random forest|breiman', 'Random forests (Breiman)'),
 (r'\bcart\b|decision tree', 'CART / decision trees'),
 (r'naive bayes', 'Naive Bayes'),
 (r'\bsvm\b|support vector', 'SVM'),
 (r'porter stemmer|stemm', 'Porter stemmer'),
 (r'hidden technical debt|sculley', 'Hidden technical debt in ML (Sculley et al.)'),
 (r'practitioner survey|90.*willing|lo et al.*survey', 'Practitioner survey on analytics adoption (Lo et al.)'),
 (r'tca\+?|transfer component', 'TCA+ (Nam et al.)'),
 (r'\btnb\b|transfer naive bayes', 'Transfer Naive Bayes (Ma et al.)'),
 (r'cpdp|cross.project defect|zimmermann.*cross|turhan.*(cross|burak|filter|nn)|burak filter|relevancy filter', 'Cross-project defect prediction baselines (Zimmermann; Turhan)'),
 (r'\bcca\b|canonical correlation|heterogeneous.*(jing|cca)', 'CCA+ heterogeneous transfer (Jing et al.)'),
 (r'\bhdp\b|heterogeneous defect', 'HDP (Nam & Kim)'),
 (r'bellwether', 'Bellwether transfer learning (Krishna & Menzies)'),
 (r'cocomo|coc81|nasa93|coconut', 'COCOMO models and data (Boehm; Menzies)'),
 (r'fastread|fast2|yu.*active|harmless', 'FASTREAD / FAST2 active learning (Yu & Menzies)'),
 (r'commit\.?guru|kamei|jit defect|just.in.time', 'JIT defect prediction (Kamei; Commit.Guru)'),
 (r'maldonado|shihab|self.admitted', 'SATD data (Maldonado & Shihab)'),
 (r'\blda\b|latent dirichlet|blei', 'LDA topic modeling (Blei et al.)'),
 (r'lda-?ga|panichella', 'LDA-GA (Panichella et al.)'),
 (r'word2vec|mikolov', 'word2vec (Mikolov et al.)'),
 (r'\bcnn\b|convolutional', 'CNN baseline (Xu et al.)'),
 (r'differential evolution|storn', 'Differential evolution (Storn & Price)'),
 (r'grid search|tantithamthavorn', 'Grid-search tuning (Tantithamthavorn et al.)'),
 (r'aif ?360|reweigh|fairness.*(baseline|ibm)|chakraborty', 'AIF360 fairness baselines (IBM)'),
 (r'flash\b|nair.*flash', 'FLASH sequential model-based optimizer (Nair et al.)'),
 (r'cherrypick|alipourfard', 'CherryPick (Alipourfard et al.)'),
 (r'hibench|spark-?perf', 'HiBench / spark-perf workloads'),
 (r'cormack|grossman|autotar|knee', 'Cormack & Grossman TAR methods'),
 (r'siegmund|apel|sprl|spl configuration|x264|berkeley db|bdbc|sqlite|llvm', 'Configurable-system performance data (Siegmund; Apel)'),
 (r'sayyad|feature model|splot|sway', 'SPL feature models / SWAY (Sayyad; Chen)'),
 (r'\bwhat\b.*spectral|spectral|where\b.*cluster|\bgale\b', 'WHERE / WHAT spectral learners (Menzies group)'),
 (r'50.?50.*split|hold.?out|cross.?validation|repeat.*randomi', 'Train/test split protocol'),
 (r'\bauc\b', 'AUC as evaluation measure'),
 (r'spearman|pearson', 'Rank / linear correlation'),
 (r'\bks test\b|kolmogorov', 'Kolmogorov-Smirnov test'),
 (r'kruskal|wilcoxon|mann.whitney', 'Wilcoxon / Mann-Whitney / Kruskal-Wallis test'),
 (r'events per variable|\bepv\b|peduzzi', 'Events-per-variable rule (Peduzzi)'),
 (r'feature (subset )?selection', 'Feature subset selection (Hall & Holmes; Kohavi & John)'),
 (r'brooks|mythical man', "Brooks's law / Mythical Man-Month"),
 (r'github showcase|github api|kalliamvakou|promises and perils', 'GitHub data and mining pitfalls (Kalliamvakou et al.)'),
 (r'crowdtest|baidu|crowd.?sourc', 'Baidu CrowdTest data and crowdsourced testing prior work'),
 (r'mahakil|bennin', 'MAHAKIL oversampling (Bennin et al.)'),
 (r'lessmann', 'Lessmann et al. benchmark of defect classifiers'),
 (r'shepperd.*(nasa|quality)|nasa data quality', 'Defect-data quality problems (Shepperd; Herbold)'),
 (r'empirical standards|ralph', 'ACM SIGSOFT Empirical Standards (Ralph et al.)'),
]
_old=canon
def canon(raw):
    t=raw.lower()
    for rx,name in RULES:
        if re.search(rx,t): return name
    for rx,name in EXTRA:
        if re.search(rx,t): return name
    return raw
