/<\/head>/{ 
  print "<script type=\"text/javascript\" src=\"http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML\"></script>"
  print "<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css\" type=\"text/css\">"
  print $0
}

/^<pre>/   { IN=1 }
IN {
gsub(/\<(True|False|None)\>/,"<font color=\"Blue\">&</font>")
gsub(/\<(and|or|not|in|is)\>/,"<font color=\"Coral\">&</font>")
gsub(/\<(if|elif|else)\>/,"<font color=\"Cyan\">&</font>")
gsub(/\<(for|while|break|continue|else)\>/,"<font color=\"GoldenRodYellow\">&</font>")
gsub(/\<(def|class|with|as|pass|lambda)\>/,"<font color=\"#79CEEE\">&</font>")
gsub(/\<(return|yield)\>/,"<font color=\"#6E89A2\">&</font>")
gsub(/\<(import|from|as)\>/,"<font color=\"Pink\">&</font>")
gsub(/\<(try|except|raise|finally|else|assert)\>/,"<font color=\"Salmon\">&</font>")
gsub(/\<(async|await)\>/,"<font color=\"SeaGreen\">&</font>")
gsub(/\<(del|global|nonlocal)\>/,"<font color=\"SkyBlue\">&</font>")
}
/<\/pre>$/ { IN=0 }
1
# https://www.pinterest.com/pin/371195194303176278/

#black", "white", "gray", "silver", "maroon", "red", "purple", "fushsia", "green", "lime", "olive", "yellow", "navy", "blue", "teal", and "aqua"),

# AliceBlue
# AntiqueWhite
# Aqua
# Aquamarine
# Azure
# Beige
# Bisque
# Black
# BlanchedAlmond
# Blue
# BlueViolet
# Brown
# BurlyWood
# CadetBlue
# Chartreuse
# Chocolate
# Coral
# CornflowerBlue
# Cornsilk
# Crimson
# Cyan
# DarkBlue
# DarkCyan
# DarkGoldenRod
# DarkGrey
# DarkGreen
# DarkKhaki
# DarkMagenta
# DarkOliveGreen
# Darkorange
# DarkOrchid
# DarkRed
# DarkSalmon
# DarkSeaGreen
# DarkSlateBlue
# DarkSlateGrey
# DarkTurquoise
# DarkViolet
# DeepPink
# DeepSkyBlue
# DimGray
# DodgerBlue
# FireBrick
# FloralWhite
# ForestGreen
# Fuchsia
# Gainsboro
# GhostWhite
# Gold
# GoldenRod
# Grey
# Green
# GreenYellow
# HoneyDew
# HotPink
# IndianRed
# Indigo
# Ivory
# Khaki
# Lavender
# LavenderBlush
# LawnGreen
# LemonChiffon
# LightBlue
# LightCoral
# LightCyan
# LightGoldenRodYellow
# LightGrey
# LightGreen
# LightPink
# LightSalmon
# LightSeaGreen
# LightSkyBlue
# LightSlateGrey
# LightSteelBlue
# LightYellow
# Lime
# LimeGreen
# Linen
# Magenta
# Maroon
# MediumAquaMarine
# MediumBlue
# MediumOrchid
# MediumPurple
# MediumSeaGreen
# MediumSlateBlue
# MediumSpringGreen
# MediumTurquoise
# MediumVioletRed
# MidnightBlue
# MintCream
# MistyRose
# Moccasin
# NavajoWhite
# Navy
# OldLace
# Olive
# OliveDrab
# Orange
# OrangeRed
# Orchid
# PaleGoldenRod
# PaleGreen
# PaleTurquoise
# PaleVioletRed
# PapayaWhip
# PeachPuff
# Peru
# Pink
# Plum
# PowderBlue
# Purple
# Red
# RosyBrown
# RoyalBlue
# SaddleBrown
# Salmon
# SandyBrown
# SeaGreen
# SeaShell
# Sienna
# Silver
# SkyBlue
# SlateBlue
# SlateGrey
# Snow
# SpringGreen
# SteelBlue
# Tan
# Teal
# Thistle
# Tomato
# Turquoise
# Violet
# Wheat
# White
# WhiteSmoke
# Yellow
# YellowGreen
