/<\/head>/{ 
  print "<script type=\"text/javascript\" src=\"http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML\"></script>"
  print "<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.0.7/css/all.css\">"
  print $0
}


/^<pre>/   { IN=1 }
/^[ \t]*\#/ { print "<font color=DarkGrey>"$0"</font>"; next}
IN {
gsub(/\<(and|or|not|in|is)\>/,"<b><font color=\"black\">&</font></b>")
gsub(/\<(if|elif|else)\>/,"<b><font color=\"black\">&</font></b>")
gsub(/\<(for|while|break|continue|else)\>/,"<b><font color=\"black\">&</font></b>")
#gsub(/\<(def|class|with|as|pass|lambda)\>/,"<b><font color=\"#00427d\">&</font></b>")
gsub(/\<(def|class|with|as|pass|lambda)\>/,"<b><font color=\"purple\">&</font></b>")
gsub(/\<(return|yield)\>/,"<font color=\"red\">&</font></b>")
gsub(/\<(try|except|raise|finally|else|assert)\>/,"<b><font color=\"black\">&</font></b>")
gsub(/\<(True|False|None)\>/,"<b><font color=\"olive\">&</font></b>")
gsub(/\<(import|from|as)\>/,"<b><font color=\"navy\">&</font></b>")
gsub(/\<(async|await)\>/,"<b><font color=\"teal\">&</font></b>")
gsub(/\<(del|global|nonlocal)\>/,"<b><font color=\"aqua\">&</font></b>")
}
/<\/pre>$/ { IN=0 }
1
# https://www.pinterest.com/pin/371195194303176278/

#need to find a good matchin color sequence from https://ethanschoonover.com/solarized/
#black", "white", "gray", "silver", "maroon", "red", "purple", "fushsia", "green", "lime", "olive", "yellow", "navy", "blue", "teal", and "aqua"),

# AliceBlue
# AntiqueWhite
# Aqua
# Aquamarine
# Azure
# Beige
# Bisque
# Black
# BlanchedAlmond
# Blue
# BlueViolet
# Brown
# BurlyWood
# CadetBlue
# Chartreuse
# Chocolate
# Coral
# CornflowerBlue
# Cornsilk
# Crimson
# Cyan
# DarkBlue
# DarkCyan
# DarkGoldenRod
# DarkGrey
# DarkGreen
# DarkKhaki
# DarkMagenta
# DarkOliveGreen
# Darkorange
# DarkOrchid
# DarkRed
# DarkSalmon
# DarkSeaGreen
# DarkSlateBlue
# DarkSlateGrey
# DarkTurquoise
# DarkViolet
# DeepPink
# DeepSkyBlue
# DimGray
# DodgerBlue
# FireBrick
# FloralWhite
# ForestGreen
# Fuchsia
# Gainsboro
# GhostWhite
# Gold
# GoldenRod
# Grey
# Green
# GreenYellow
# HoneyDew
# HotPink
# IndianRed
# Indigo
# Ivory
# Khaki
# Lavender
# LavenderBlush
# LawnGreen
# LemonChiffon
# LightBlue
# LightCoral
# LightCyan
# LightGoldenRodYellow
# LightGrey
# LightGreen
# LightPink
# LightSalmon
# LightSeaGreen
# LightSkyBlue
# LightSlateGrey
# LightSteelBlue
# LightYellow
# Lime
# LimeGreen
# Linen
# Magenta
# Maroon
# MediumAquaMarine
# MediumBlue
# MediumOrchid
# MediumPurple
# MediumSeaGreen
# MediumSlateBlue
# MediumSpringGreen
# MediumTurquoise
# MediumVioletRed
# MidnightBlue
# MintCream
# MistyRose
# Moccasin
# NavajoWhite
# Navy
# OldLace
# Olive
# OliveDrab
# Orange
# OrangeRed
# Orchid
# PaleGoldenRod
# PaleGreen
# PaleTurquoise
# PaleVioletRed
# PapayaWhip
# PeachPuff
# Peru
# Pink
# Plum
# PowderBlue
# Purple
# Red
# RosyBrown
# RoyalBlue
# SaddleBrown
# Salmon
# SandyBrown
# SeaGreen
# SeaShell
# Sienna
# Silver
# SkyBlue
# SlateBlue
# SlateGrey
# Snow
# SpringGreen
# SteelBlue
# Tan
# Teal
# Thistle
# Tomato
# Turquoise
# Violet
# Wheat
# White
# WhiteSmoke
# Yellow
# YellowGreen
