#!/usr/bin/env gawk -f
# vim: filetype=awk ts=2 sw=2 sts=2  et :

     { gsub(/[\r\t ]*/,"",$0) 
       gsub(/#.*/,"",$0)
     }
/^$/ { next}
/,$/ { b4 = b4 ? b4 "\n" $0 : $0 ; next}
     { print b4 $0; b4="" }
