#!/usr/bin/env gawk -f
# vim: filetype=awk ts=2 sw=2 sts=2  et :

BEGIN      { FS="," }
NR==1      { Want=NF; print; next }
NR != Want {
      print "#W> Skipping row "NR": has not "Want" fields">"/dev/stderr" 
      next}
     { for(i=1;i<=NF;i++)
         if ($i !~ /\?/)
           use[++n]= i}
     { printf($use[1])
       for(i=2;i<=n;i++) printf("," $use[i] ) }
