# title: Data Mining for Very Busy People
clean1 : ; @cat data/bad.csv | clean
col1   : ; @$(MAKE) clean1  | cols 


# too few entries in bin1 of humidity
# bin1 tabkeing input NOT from input stream
bins1  : ; @$(MAKE) col1 | bins


