#!/usr/bin/env bash
# vim: set nospell :
#--------- --------- --------- --------- --------- ---------

Base="https://raw.githubusercontent.com/timm/misc/master/gold"

help() { cat<<-EOF
	au          : regenerate awk files
	au reset    : kill old awk then regenerate
	au XXX      : run gawk -f XXX
	EOF
}

goldrc() { cat<<-EOF
	export Gold="$(PWD)"
	export GoldAwk="$HOME/opt/gold"
	export AWKPATH="$HOME/opt/gold:$AWKPATH"
	export PATH="$HOME/opt/gold:$PATH"
	EOF
}

gold2awk() { gawk '
  BEGIN { In=1 }
  NR==1 { print "#!/usr/bin/env gawk -f "; next }
  
  # convert multi-line strings to commented lines
  
  gsub(/^"""/,"") { In =  1 - In  }
                  { pre  = In ? "" : "# " }
  
  # catch the current function name (needed for isa)
  In && /^[ \t]*function[ \t]+/ {
  	Fun=gensub(/^[ \t]*function[ \t]+([_A-Za-z0-9]+).*/,
               "\\1","g",$0)	
  }
  
  # let isa add link kid class to parent class as well
  # as do some object initializations
  In && /^[ \t]*isa\(/ {
  	$0= gensub(/(^[ \t]*)isa\((([_A-Za-z0-9]+)\(([^,\)]+).*)/,
  	             "\\1isa(\\4,\""Fun"\",\"\\3\",\\2","g",$0)
  }
  
  # allow polymoprhism lookup
  In && /@[A-Z]/ {
  	$0= gensub(/@([A-Z].+)(\(([^,\)]+)[,\)])/, 
               "(MY=my(\\3,\"\\1\"))@MY\\2","g",$0)
  }
  
  # allow dot notation
  In {
    if ($0 !~ /^@include/) 
      $0 = gensub(/\.([^0-9])([a-zA-Z0-9_]*)/,
                  "[\"\\1\\2\"]", "g", $0) 
  }
  
  { print pre $0 } 
'
}

zap()     { 
  [ -n "$GoldAwk" ] && rm  $GoldAwk/*.awk 2> /dev/null 
}

ready() {
  f=lib/gold.gold
  if [ ! -f "$f" ]; then
    mkdir -p lib
    wget -O $f  "$Base/rocks/$f"
  fi
  if [ ! -f "$HOME/.config/gold" ]; then
    mkdir -p $HOME/.config
    goldrc > $HOME/.config/gold 
  fi
}

regenerate() {
  mkdir -p $GoldAwk
  files=$(find $Gold -name '*.gold')
  for f in $files; do
    g=$(basename $f)
    g=$GoldAwk/${g%.gold}.awk
    if [ "$f" -nt "$g" ]  ; then
      cat $f | gold2awk > $g
      chmod +x $g
    fi
    echo $(basename $f)
  done |
  gawk 'Seen[$0]++ {print "#E> repeated file name " $0 > "/dev/stderr"}' 
}  

ready
. $HOME/.config/gold

if   [ "$1" == "help"    ]; then help
elif [ "$1" == "reset"   ]; then zap; regenerate
else regenerate
     [ -n "$*" ] && AWKPATH="$AWKPATH" gawk -f $*
fi
