#!/usr/bin/env bash

GOLDgh="https://raw.githubusercontent.com/timm/misc/master/gawk"
GOLDbase="blank test object lib"

GOLD=${GOLD:-/tmp/gold}
mkdir -p $GOLD

compile() {  gawk '
function shared(s,     f,args,   b,tmp) {
  split(s,b,/[()]/)
  f    = b[1]
  args = b[2]
  tmp  = "_t_m_p_"int(rand()*100000)
  return "function " f "(" args "," tmp ") { "\
             tmp"=how(i[\"is\"],\""f"\"); return @" tmp "(" args")}" 
}

/^shared/ { sub(/shared/,""); print shared($1); next  }
          { print gensub(/\.([^0-9])([a-zA-Z0-9_]*)/, 
                         "[\"\\1\\2\"]","g",$0) }' 
}

if [ "$(which wget)" ]; then
   for f in ${GOLDbase}; do
     if [ ! -f "${f}.gold" ]; then
       wget -O ${f}.gold ${GOLDgh}/${f}.gold
     fi
   done
fi


for f in *.gold; do
  g=$GOLD/$(basename $f .gold).awk
  if [ "$f" -nt "$g" ] ; then
    cat $f | compile > $g
  fi
done

if [ -n "$1" ]; then
  g=$GOLD/$(basename $1 .gold).awk
  shift
  AWKPATH="$GOLD:." gawk -f $g $*
fi
