#!/usr/bin/env bash

gold={gold:-/tmp/gold}
echo $gold

mkdir -p $gold

compile() {  
  gawk '
  function shared(s,     f,args,   b,tmp) {
    split(s,b,/[()]/)
    f    = b[1]
    args = b[2]
    tmp  = "tmp"int(rand()*100000)
    return "function " f "(" args "," tmp ") { "\
               tmp"=how(i[\"is\"],\""f"\"); return @" tmp "(" args")}"
  }
  
  /^shared/ { sub(/shared/,""); print shared($1); next  }
            { print gensub(/\.([^0-9])([a-zA-Z0-9_]*)/, 
                           "[\"\\1\\2\"]","g",$0)
            }
  ' 
}

update() {
  for i in *.awk; do
    if [ "$i" -nt "$gold/$i" ]; then
      cat $i | compile  > $gold/$i
    fi
  done
}

#update   
#f=$1; shift; AWKPATH="$gold" gawk -f $f $*
