#!/usr/bin/env bash

in=$1
stem=$(basename $1 .au)
out=/tmp/$stem$$.awk

cat $1 | gawk '
function shared(s,     f,args,   b,tmp) {
  split(s,b,/[()]/)
  f    = b[1]
  args = b[2]
  tmp  = "tmp"int(rand()*100000)
  return  "function " f "(" args "," tmp ") { "\
                tmp"=how(i,\""f"\"); return @" tmp "(" args")}"
}
function class(s, a) {
  split(s,a,/\(/) 
  return a[1]; 
}

/^shared/  {sub(/shared/,""); print shared($1); next  }
/^class/                 {  _ = class($2); sub(/^class/,"func")}
                         { gsub(/_/,_,$0) }
                         { print gensub(/\.([^0-9])([a-zA-Z0-9_]*)/,
                                "[\"\\1\\2\"]","g",$0)}
END {for(f in funs) print funs[f]}
' > $out

shift

#gawk -f $out $*
cat $out
