#!/usr/bin/env bash
# vim: set nospell ts=2 sw=2 sts=2 et :
#--------- --------- --------- --------- --------- ---------

Base="https://raw.githubusercontent.com/timm/misc/master/gold"
f=goldrc
if   [ -f "$f"    ]; then . $f 
elif [ -f "../$f" ]; then . ../$f
else cat<<'EOF'> $f
if [ -z "$Gold" ]; then
export Gold="$(PWD)"
export Lib="$HOME/opt/gold"
export AWKPATH="$Lib:$AWKPATH"
export PATH="$Lib:$PATH"
fi
EOF
. $f
fi


### turn .au into .awk
au2awk() {
 gawk '

BEGIN {In=1}
NR==1 { print "#!/usr/bin/env gawk -f "; next }

# convert multi-line strings to commented lines

gsub(/^"""/,"") { In =  1 - In  }
                { pre  = In ? "" : "# " }

# catch the current function name (needed for isa)
In && /^[ \t]*function[ \t]+/ {
	Fun=gensub(/^[ \t]*function[ \t]+([_A-Za-z0-9]+).*/,
             "\\1","g",$0)	
}

# make isa also add links kids to parents
In && /^[ \t]*isa\(/ {
	$0= gensub(/(^[ \t]*)isa\((([_A-Za-z0-9]+)\(([^,\)]+).*)/,
	             "\\1isa(\\4,\""Fun"\",\"\\3\",\\2","g",$0)
}

# add polymoprhism lookup
In && /@[A-Z]/ {
	$0= gensub(/@([A-Z].+)(\(([^,\)]+)[,\)])/, 
             "(MY=my(\\3,\"\\1\"))@MY\\2","g",$0)
}

# add in dot notation
In {
  if ($0 !~ /^@include/) 
    $0 = gensub(/\.([^0-9])([a-zA-Z0-9_]*)/,
                "[\"\\1\\2\"]", "g", $0) 
}

{ print pre $0 } '
}

### zap old awks
if [ "$1" == "help"  ]; then
  cat<<EOF

./79 install   : install base files
./79 zap       : kill all generated awk files
./79           : regenerate awk files
./79 XXX       : run gawk -f XXX
EOF
elif [ "$1" == "zap"  ]; then
  rm  $Lib/*.awk 2> /dev/null
elif [ "$1" == "install" ]; then
  chmod +x 79
  if [ ! -f "gold.au" ]; then
    wgey -O gold.au "$Base/gold.au"
  fi
  if [ ! -f "goldrc" ]; then
    wget -O goldrc "$Base/etc/rc"
  fi
else
  mkdir -p $Lib

  ### update files
  for f in $Gold/gold.au $Gold/*/*.au ; do
    g=$(basename $f)
    g=$Lib/${g%.au}.awk
    if [ "$f" -nt "$g" ]  ; then
      cat $f | au2awk > $g
      chmod +x $g
    fi
    echo $(basename $f)
  done |
  gawk 'Seen[$0]++ {print "#E> repeat " $0}' 2> /dev/stderr
  
  ### if any command line args, run them
  if [ -n "$Todo" ]; then
     AWKPATH="$AWKPATH" gawk -f $*
  fi
fi
