#!/usr/bin/env bash
## help sh/all : : show all the the local functions
Here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo -e "\n\033[36mcommands:\033[0m"
gawk -F: 'sub(/^## help /,""){ \
              printf "  \033[33m%10s\033[0m %-6s : %s\n",$1,$2,$3 \
         }' $Here/*

