#!/usr/bin/env bash

footer() { cat<<'EOF'
BEGIN{  DOT=sprintf("%c",46)}

function oo(x,p,pre, i,txt) {
  txt = pre ? pre : (p DOT)
  ooSortOrder(x)
  for(i in x)  {
    if (isarray(x[i]))   {
      print(txt i"" )
      oo(x[i],"","|  " pre)
    } else
      print(txt i (x[i]==""?"": ": " x[i])) }
}
function ooSortOrder(x, i) {
  for (i in x)
    return PROCINFO["sorted_in"] =\
      typeof(i+1)=="number" ? "@ind_num_asc" : "@ind_str_asc"
}

function rogues(    s) {
  for(s in SYMTAB) if (s ~ /^[A-Z][a-z]/) print "Global " s>"/tty/stderr"
  for(s in SYMTAB) if (s ~ /^[_a-z]/    ) print "Rogue: " s>"/ttr/stderr"
}

function tests(what, all,   one,a,i,n) {
  n = split(all,a,",")
  print "\n#--- " what " -----------------------"
  for(i=1;i<=n;i++) { one = a[i]; @one(one) }
  rogues()
}

function ok(f,got,want,   epsilon,     ok) {
  if (typeof(want) == "number") {
     epsilon = epsilon ? epsilon : 0.001
     ok = abs(want - got)/(want + 10^-32)  < epsilon
  } else
     ok = want == got
  if (ok)
    print "#TEST:\tPASSED\t" f "\t" want "\t" got
  else
    print "#TEST:\tFAILED\t" f "\t" want "\t" got
}

function zap(i,k)  { k = k?k:length(i)+1; i[k][0]; List(i[k]); return k } 

function List(i)         { split("",i,"") }
function Object(i)       { List(i); i["oid"]=++OID }

function is( i,k,f)      { f=f?f:"List"; zap(i,k); @f(i[k]) }
function isa(i,k,f,m)    {               zap(i,k); @f(i[k],m) }
function isas(i,k,f,m,n) {              zap(i,k); @f(i[k],m,n) }

END { rogues() }

EOF
}
parse() { gawk '
  /^@include/              { print "CODE "$0; next }
  /^(func|BEGIN|END).*}$/  { print "CODE "$0; next }
  /^(func|BEGIN|END)/,/^}/ { print "CODE "$0; next }
                           { print "DOC " $0} '
}

gen() {
gawk '
  function prep(s) {
    print gensub(/\.([^0-9])([a-zA-Z0-9_]*)/,
                  "[\"\\1\\2\"]","g",s) }

  sub(/^DOC /,"#")         { print; next }
                           { gsub(/(CODE |[ \t]*$)/,"")   }
  /^@include/              { prep($0); next }
  /^(func|BEGIN|END).*}$/  { prep($0); next }
  /^(func|BEGIN|END)/,/^}/ { prep($0); next }
                           { print "# " $0  } '
}

cat  $1  | parse | gen > /tmp/$$$1
shift
gawk -f /tmp/$$$1 $*
