#!/usr/bin/env bash

prefix=${1:-Web}
files="$(find . -type f)"
com=/tmp/$$.com
for f in $files; do
  if [ ! "$f" == "." ]; then
    d=$(dirname $f)
    echo mkdir -p $d 
  fi
done | sort | uniq > $com
bash $com
all=""
for f in $files; do
  if [ ! "$f" == "." ]; then
    t=$prefix$(echo $f | sed 's/[\.\/]/_/g')
    all="$all $f"
    cat<<-EOF
	$f : ; @echo "\$\$$t" > \$@; git add \$@
	    
	define $t
	`sed 's/\\$/$$/g' $f`
	endef
	export $t
	
	EOF
  fi
done
echo "$prefix : $all"
