#!/usr/bin/env gawk   -f

# Function to process tags in the text
function s(t, i) {
    while (match($0, t)) {
        if (I[ni] == i) {
            ni -= sub(t, "</" i ">")  # Close tag
        } else if (sub(t, "<" i ">")) {
            I[++ni] = i  # Open tag
        }
    }
}

# BEGIN block to initialize field and record separators and index
BEGIN {
    FS = "\n"      # Field separator: newline
    RS = ""        # Record separator: blank lines (paragraph mode)
    ni = 0         # Initialize nesting index
}

# Main block to process each record
/^<pre>/   { 
    gsub(/</,"\\&lt;"); 
    gsub(/\<(and|or|not|in|is)\>/, "<b><font color=black>&</font></b>")
    gsub(/\<(if|else|while|for|do|break|continue|exit)\>/, "<b><font color=blue>&</font></b>")
    gsub(/\<(length|substr|match|split|index|sprintf|gsub|sub|tolower|toupper|system|close)\>/, "<b><font color=green>&</font></b>")
    gsub(/\<(BEGIN|END|NR|NF|FS|OFS|RS|ORS|FILENAME|ARGV|ARGC)\>/, "<b><font color=purple>&</font></b>")
    gsub(/\<(print|printf|getline)\>/, "<b><font color=red>&</font></b>")
    gsub(/\<(true|false|null)\>/, "<b><font color=olive>&</font></b>")
    gsub(/\<(getline|next|nextfile|close)\>/, "<b><font color=teal>&</font></b>")
    print "<pre>"
    for(i=2;i<NF;i++) {print $i } 
    print "</pre>"
    next}

{
    # Wrap non-tagged text in <p> tags
    $0 = (match($0, /^<.*>$/)) ? $0 : "<p>" $0 "</p>"

    # Process formatting for strong, em, and code tags
    s("__", "strong")
    s("\\*", "em")
    s("`", "code")

    # Print the processed record
    print
}
