#!/usr/bin/env bash
file="${1%.*}"         # strip .py if present
src="$file.py"         # assumes .py file
ps=~/tmp/$file.ps
pdf=~/tmp/$file.pdf

enscript -B -r -C \
  --columns=4 \
  --lines-per-page=500 \
  --font=Courier4\
  --margins=10:10:10:10 \
  -Epython \
  --color \
  -o ~/tmp/ezr.ps ezr.py && \
ps2pdf ~/tmp/ezr.ps ~/tmp/ezr.pdf && \
rm ~/tmp/ezr.ps

