#!/usr/bin/env bash
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Usage: ./rq1  file1 file2 ...

if [ -z "$1" ]; then
  echo "Usage: rq1 rxFiles"
  exit
fi
out="$HOME/tmp/$(basename "$0")"

if [ "$1" != "--report" ]; then
  tmp=$(mktemp -d)
  for f in "$@"; do
    name="$(basename "$f" .csv)"  # strip path and optional .csv
    out_file="$tmp/$name.csv"
    echo "Running: $name" >&2
    python3 -B "$DIR/../ezr.py" -f "$f" --rq1 > "$out_file" &
  done
  wait
  cat "$tmp"/*.csv > "$out"
fi 

(cat "$out" | gawk -F, '{ print $(NF), $0 }' | sort -n -k1,1 | cut -d' ' -f2- 
cat "$out" | gawk -F, -f $DIR/rq1.awk ) | column -s, -t | grep --color A

