#!/usr/bin/env bash
# vim: ft=sh ts=2 sw=2 et :

here=$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )

want=$here/.gitignore
[ -f "$want" ] || cat<<EOF>$want
*.awk
EOF

for f in *.au; do
  g=${f%.*}.awk
  if [ "$f" -nt "$g" ]; then
    gawk ' {print gensub( /\.([^0-9\\*\\$\\+])([a-zA-Z0-9_]*)/, 
                          "[\"\\1\\2\"]","g", $0)}' $f > $g
  fi
done

if [ -n "$1" ]; then
  g=${1%.*}.au
  shift
  if [ -t 1 ]
  then         gawk -f $g $*
  else cat - | gawk -f $g $*
  fi
fi
