#!/usr/bin/env bash
# vim: ft=sh ts=2 sw=2 et :
here=$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )

chmod +x $here/gold
mkdir -p $here/docs

want=$here/.gitignore
[ -f "$want" ] || cat<<EOF>$want
*.awk
EOF

body() { gawk '
  BEGIN { Comment = "" }
  #sub(/^\|#/,"")        { Comment=0; print "# " $0 ; next}
  #sub(/^#\|[ \t]*/,"")  { Comment=1; print "# " $0 ; next}
  #Comment               { print $0                 ; next}
  sub(/^# # /,   "")     { print "# " $0   ; Pre="## "   ; next}
  sub(/^# ## /,   "")    { print "## " $0  ; Pre="### "  ; next}
  sub(/^# ### /,   "")   { print "### " $0 ; Pre="#### " ; next}
  sub(/^# #### /,   "")  { print "#### " $0; Pre="##### "; next}
  /^## /   { 
    while(sub(/^## /,"")) {
      Body = Body "\n" $0
      if(getline<1) break
    }
    Preamble=1
  }
  Preamble && /^function/ { 
    if ($0 ~ /^function/) {
      n=split($0, a, /[ \t(),]/) 
      for(i=3;i<=n;i++) {
        if (a[i] !~ /:/) break
        Sig = Sig Sep a[i]
        Sep = ", "
      }
      print Pre a[2] "\n`"a[2]"("Sig")`"
      print Body
      print "\n<ul><details><summary>...</summary>" 
      print "\n```awk" 
  }}
  Preamble &&  $0  { print }
  Preamble && !$0  {   
      Preamble = 0
      Body=Sep=Sig=""
      print "```"
      print "\n</details></ul>\n\n" 
  }
  END { if(Preamble) print "```" }
  '
}
toc() { gawk '
  function ns(n,    s) { while(n-- > 0) s= s "  "      ; return s}
  function trim(s)     { gsub(/(^[ \t]*|[ \t]*$)/,"",s); return s}
       { Body = Body "\n" $0 }
  /^#/ { prefix = ns(length($1)-1 )
         $1=""
         $0= trim($0)
         split($0,a,")")
         text = a[1]")"; help=a[2]
         gsub(/[^[:alpha:]]/,"",$0)
         if (help)
           print(prefix "- ["text"](#"tolower($0)") : " help)
         else
           print(prefix "- ["text"](#"tolower($0)") " )
  }
  END {print Body} '
} 
transpile() { gawk  '
  BEGIN            { Comment="" }
  sub(/^\|#/,"")   { Comment=""  ; print; next}
  sub(/^#\|[ \t]*/,"")   { Comment="# "; print; next}

  /^func(tion)?[ \t]+[A-Z][^\(]*\(/ {
      split($0,a,/[ \t\(]/)
      PREFIX = a[2]
  }
  { gsub(/ _/," " PREFIX,$0)
    print Comment  gensub( /\.([^0-9\\*\\$\\+])([a-zA-Z0-9_]*)/, 
                      "[\"\\1\\2\"]","g", $0)} '
} 
for f in *.gold; do
  g=${f%.*}.awk
  if [ "$f" -nt "$g" ]; then 
    cat $f | transpile> $g
  fi
done

if [ "$1" == "docs" ]; then
   for f in *.gold; do
     g=$here/docs/${f%.*}.md
     if [ "$f" -nt "$g" ]; then 
       echo "# $f"
       echo "# " $f > $g
       cat $f | body | toc >> $g
     fi
   done
elif [ "$1" == "push" ]; then
  git config advice.addIgnoredFile false
  git add *
  git commit -am saving
  git push
  git status
elif [[ "$1" =~ ^.*gold$ ]] ; then
  g=${1%.*}.awk
  shift
  if [ -t 1 ]
  then         gawk -f $g $*
  else cat - | gawk -f $g $*
  fi
elif [ -n "$1" ]; then
  echo "?"
fi
